on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
    - completed
jobs:
  check_links:
    runs-on: ubuntu-20.04
    steps:
    - name: Check links with linkcheck
      uses: filiph/linkcheck@v2.0.15+1
      with:
        arguments: https://skyconqueror.de/
            
